"""
build_embedded_data.py — Sync embedded data into priority_tool.html

Reads schema/reference_configs/*.json and sample_projects.csv, then injects
them into priority_tool.html between the BEGIN_EMBEDDED_DATA and
END_EMBEDDED_DATA markers. Idempotent — re-running produces the same output
unless the source files have changed.

This keeps the configurator working as a static file (per APH's
'no backend required' principle in ARCHITECTURE_v2.md) while keeping the
JSON configs as the source of truth.

Usage:
    cd APH/tools/priority_model_tool
    python3 build_embedded_data.py
"""

from __future__ import annotations

import csv
import json
import re
from pathlib import Path

HERE = Path(__file__).parent
HTML = HERE / "priority_tool.html"
CONFIGS = HERE / "schema" / "reference_configs"
PROJECTS_CSV = HERE / "sample_projects.csv"

BEGIN_MARKER = "// BEGIN_EMBEDDED_DATA"
END_MARKER = "// END_EMBEDDED_DATA"


def collect_reference_configs():
    """Return {filename_stem: parsed_json} for every reference config."""
    out = {}
    for p in sorted(CONFIGS.glob("*.json")):
        out[p.stem] = json.loads(p.read_text())
    return out


def collect_sample_projects():
    """Return list of dicts from sample_projects.csv with light type coercion."""
    rows = []
    with PROJECTS_CSV.open(newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            # Coerce numeric and boolean strings for embedded use
            row = {}
            for k, v in r.items():
                if v == "":
                    row[k] = ""
                elif v.lower() in ("true", "yes"):
                    row[k] = True
                elif v.lower() in ("false", "no"):
                    row[k] = False
                else:
                    try:
                        row[k] = int(v) if "." not in v else float(v)
                    except (ValueError, TypeError):
                        row[k] = v
            rows.append(row)
    return rows


def render_block(configs: dict, projects: list) -> str:
    js_configs = json.dumps(configs, indent=2)
    js_projects = json.dumps(projects, indent=2)
    return (
        f"  {BEGIN_MARKER}\n"
        f"  // Auto-generated by build_embedded_data.py — do not edit by hand.\n"
        f"  // Reference configs (4 reference state models):\n"
        f"  window.PM_REFERENCE_CONFIGS = {js_configs};\n\n"
        f"  // Sample projects (25 synthetic projects for live preview):\n"
        f"  window.PM_SAMPLE_PROJECTS = {js_projects};\n"
        f"  {END_MARKER}"
    )


def inject(html_text: str, block: str) -> str:
    """Replace the content between BEGIN/END markers (inclusive) with `block`."""
    pattern = re.compile(
        r"(\s*)" + re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    if not pattern.search(html_text):
        raise SystemExit(
            f"Markers not found in {HTML.name}. Add:\n"
            f"  {BEGIN_MARKER}\n  ...\n  {END_MARKER}\n"
            f"inside a <script> block before running this builder."
        )
    return pattern.sub(lambda m: m.group(1).split('\n')[0] + block, html_text, count=1)


def main():
    if not HTML.exists():
        raise SystemExit(f"{HTML} does not exist yet. Create the HTML scaffold first.")
    configs = collect_reference_configs()
    projects = collect_sample_projects()
    block = render_block(configs, projects)
    html_text = HTML.read_text()
    new_html = inject(html_text, block)
    if new_html == html_text:
        print(f"No changes to {HTML.name}.")
    else:
        HTML.write_text(new_html)
        print(f"Updated {HTML.name}: embedded {len(configs)} configs and {len(projects)} sample projects.")


if __name__ == "__main__":
    main()
